apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: portforge/auth-service
        property: database-url
    - secretKey: secret-key
      remoteRef:
        key: portforge/auth-service
        property: secret-key
    - secretKey: aws-access-key
      remoteRef:
        key: portforge/auth-service
        property: aws-access-key
    - secretKey: aws-secret-key
      remoteRef:
        key: portforge/auth-service
        property: aws-secret-key
    - secretKey: cognito-userpool-id
      remoteRef:
        key: portforge/auth-service
        property: cognito-userpool-id
