apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: support-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: support-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: portforge/support-service
        property: DATABASE_URL
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: portforge/support-service
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: portforge/support-service
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: DDB_ENDPOINT_URL
      remoteRef:
        key: portforge/support-service
        property: DDB_ENDPOINT_URL
    - secretKey: COGNITO_USERPOOL_ID
      remoteRef:
        key: portforge/support-service
        property: COGNITO_USERPOOL_ID
    - secretKey: COGNITO_APP_CLIENT_ID
      remoteRef:
        key: portforge/support-service
        property: COGNITO_APP_CLIENT_ID
