apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: team-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: portforge/team-service
        property: database-url
    - secretKey: db-host
      remoteRef:
        key: portforge/team-service
        property: db-host
    - secretKey: db-port
      remoteRef:
        key: portforge/team-service
        property: db-port
    - secretKey: db-name
      remoteRef:
        key: portforge/team-service
        property: db-name
    - secretKey: db-username
      remoteRef:
        key: portforge/team-service
        property: db-username
    - secretKey: db-password
      remoteRef:
        key: portforge/team-service
        property: db-password
    - secretKey: jwt-secret
      remoteRef:
        key: portforge/team-service
        property: jwt-secret
    - secretKey: aws-access-key
      remoteRef:
        key: portforge/team-service
        property: aws-access-key
    - secretKey: aws-secret-key
      remoteRef:
        key: portforge/team-service
        property: aws-secret-key
